---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.1 enthält eine neue Verbesserung. 
---
= Neuerungen bei Cloud Volumes ONTAP 9.13.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.1 enthält neue Verbesserungen.

Zusätzliche Funktionen und Erweiterungen sind ebenfalls in den neuesten Versionen von BlueXP verfügbar. Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Entsprechende Details.



== 9.13.1 P12 (25. November 2024)

Der 9.13.1 P12-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P12["Sehen Sie sich die Liste der Fehler an, die im P12-Patch behoben wurden"^] (Anmeldung auf der NetApp Support-Website erforderlich).



== 9.13.1 P11 (14. Oktober 2024)

Der 9.13.1 P11-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P11["Zeigen Sie die Liste der im P11-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support-Website erforderlich).



== 9.13.1 P10 (8. August 2024)

Der 9.13.1 P10-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P10["Zeigen Sie die Liste der im P10-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support-Website erforderlich).



== 9.13.1 P9 (22. Mai 2024)

Der 9.13.1 P9-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P9["Zeigen Sie die Liste der im P9-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 P8 (18. April 2024)

Der 9.13.1 P8-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P8["Zeigen Sie die Liste der im P8-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 P7 (1. April 2024)

Der 9.13.1 P7-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P7["Zeigen Sie die Liste der im P7-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 P6 (5. Februar 2024)

Der 9.13.1 P6-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Anbieter verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P6["Zeigen Sie die Liste der im P6-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 P4 (8. Dezember 2023)

Der 9.13.1 P4-Patch ist jetzt für Cloud Volumes ONTAP für alle Cloud-Provider verfügbar. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P4["Hier finden Sie eine Liste der im P4-Patch fixierten Fehler"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 P2 und 9.13.1 P3 (20. Oktober 2023)

Die Patches 9.13.1 P2 und 9.13.1 P3 stehen jetzt für Cloud Volumes ONTAP für alle Cloud-Provider zur Verfügung, wenn Sie einen Connector mit Version 3.9.26 oder höher haben. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P3["Zeigen Sie die Liste der im P3-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).
* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P2["Zeigen Sie die Liste der im P2-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).




== 9.13.1 P1 (3. Oktober 2023)

Der Patch 9.13.1 P1 ist jetzt für Cloud Volumes ONTAP für alle Cloud-Anbieter verfügbar, wenn Sie einen Connector mit Version 3.9.26 oder höher haben. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P1["Zeigt die Liste der im P1-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.13.1 GA (26. Juli 2023)

Die allgemeine Verfügbarkeit von Cloud Volumes ONTAP 9.13.1 ist jetzt in AWS, Azure und Google Cloud verfügbar.



== 9.13.1 RC1 (26. Juni 2023)

Der Release Candidate 1 von Cloud Volumes ONTAP 9.13.1 ist jetzt in AWS, Azure und Google Cloud verfügbar.

Einige FabricPool-Performance-Verbesserungen können sich auf Ihre Tiering-Daten in Cloud Volumes ONTAP auswirken.

.Verbesserungen bei sequenzieller Lesegeschwindigkeit und Tiering
Aufgrund der verbesserten Lese-Performance und des Tiering-Durchsatzes in FabricPool kann es zu einer höheren Rate von `GET` und `PUT` Operationen in lokalen Objektspeichern kommen. Stellen Sie sicher, dass genügend Performance-Reserven vorhanden sind, um eine nahtlose Performance zu erzielen.

Weitere Informationen finden Sie im https://www.netapp.com/media/17239-tr-4598.pdf["FabricPool Best Practices-Leitfaden"^]

.Aggressive Vorauslesefunktion
Mithilfe der `Aggressive Readahead` FabricPool Funktion können die Lesevorgänge auf Dateiebene erhöht werden. Dies wiederum kann die Lesekosten und die Speicherauslastung in der Public Cloud in sich bringen.

Weitere Informationen finden Sie in der ONTAP Dokumentation: https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-aggressive-read-ahead-task.html#enable-aggressive-read-ahead-mode-during-volume-creation["Aktivieren und deaktivieren Sie den aggressiven Read-Ahead-Modus"^]

.Cloud-Write-Funktion
Diese Funktion ermöglicht NFS-Clients den direkten Schreibvorgang in der Kapazitäts-Tier in FabricPool. Diese Funktion hat bestimmte Einschränkungen und sollte mit Vorsicht verwendet werden. Wenn beispielsweise der NFS-Datenverkehr mit Cloud-Schreibvorgängen zum regulären ONTAP-Traffic wie SnapMirror hinzugefügt wird, kann dies Auswirkungen auf die Recovery Point Objective (RPO) und die Recovery Time Objective (RTO) in SnapMirror haben.

Weitere Informationen finden Sie in der ONTAP Dokumentation: https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-volume-cloud-write-task.html["Aktivieren und deaktivieren Sie Volumes für einen direkten Schreibvorgang in die Cloud"^]



== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen von BlueXP abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie aktualisiert werden können, wenn Sie von BlueXP benachrichtigt werden"^].



=== Unterstützter Upgrade-Pfad

Sie können von den Versionen 9.12.1 und 9.13.0 auf Cloud Volumes ONTAP 9.13.1 aktualisieren. Unter BlueXP werden Sie aufgefordert, qualifizierte Cloud Volumes ONTAP-Systeme auf diese Version zu aktualisieren.



=== Erforderliche Version des Connectors

Der BlueXP Connector muss mit Version 3.9.26 oder höher ausgeführt werden, um neue Cloud Volumes ONTAP 9.13.1 Systeme zu implementieren und vorhandene Systeme auf 9.13.1 zu aktualisieren.


TIP: Automatische Upgrades des Connectors sind standardmäßig aktiviert, sodass Sie die neueste Version verwenden sollten.



=== Ausfallzeit

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.




=== c4-, m4- und r4-Instanzen werden nicht mehr unterstützt

In AWS werden die Instanztypen c4, m4 und r4 EC2 nicht mehr mit Cloud Volumes ONTAP unterstützt. Wenn Sie ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 zu einem Instanztyp wechseln. Sie können erst auf dieses Release aktualisieren, wenn Sie den Instanztyp ändern.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.
